import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import TopBanner from "../components/topBanner/TopBanner";
import Market from "../components/market/Market";
import CardGallery from "../components/cardGallery/CardGallery";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBanner />
      <Market />
      <CardGallery header={<h3>Inspiration for your next adventure</h3>} />
    </>
  );
}
